[package]
name = "vide"
version = "0.1.0"
edition = "2021"

[features]
default = ["ffmpeg", "preview"]
ffmpeg = ["vide_export"]
preview = ["vide_lib/preview"]


[dependencies]
vide_export = { path = "../crates/vide_export", optional = true }
vide_lib = { path = "../crates/vide_lib" }
