[workspace]
members = [
  "crates/vide",
  "crates/vide-export",
  "examples/animation",
  "examples/easing",
  "examples/audio_visualizer",
]
resolver = "2"

[workspace.dependencies]
vide = { path = "crates/vide" }
vide-export = { path = "crates/vide-export" }
