[package]
name = "audio_visualizer"
version = "0.1.0"
edition = "2021"

[dependencies]
env_logger.workspace = true
vide.workspace = true
vide-export.workspace = true
spectrum-analyzer = "1.5.0"
hound = "3.5.1"
log = "0.4.20"
